apiVersion: v1
kind: Service
metadata:
  name: store-customer-py-ws-service
spec:
  selector:
    app: store-customer-py-ws
  ports:
    - protocol: TCP
      port: 3020
      targetPort: 3020
  type: NodePort
